package com.iot_edge.managementconsole.constants;


public enum NotificationType {
    GENERAL,
    OTP,
    PROFILE_UPDATED,
    REGISTRATION,
    SUBSCRIPTION_PLAN_PURCHASED,
    SCHOOL_ADMIN_REGISTRATION,
    GUARDIAN_INVITE_BY_SCHOOL_ADMIN,
    GUARDIAN_INVITE_BY_GUARDIAN,
    EMPLOYEE_REGISTRATION,
    GUARDIAN_UNLINK,
    CHILD_APPLICATION_REJECTION,
    CHILD_REMOVAL_FROM_SCHOOL,
    COURSE_COMPLETION_CERTIFICATE,
    COURSE_PURCHASE_CONFIRMATION
}

